"use client"

// import SupabaseProvider from '@/providers/SuperProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react'
import { RecoilRoot, useRecoilState } from 'recoil'
import RecoilContextProvider from './RecoilContextProvider'


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const [isClient, setIsClient] = useState(false)
  
  // useEffect(() => {
  //   setIsClient(true)
  // }, [])

  // if (!isClient) return null
  // console.log({isClient})


  return (
    <html lang="en">
      <body className="bg-black">
        <RecoilRoot>
          {children}
        </RecoilRoot>
      </body>
    </html>
  )
}
